import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_destinationPreviewWindow(object):
    def setupUi(self, destinationPreviewWindow, selectedItem):
        self.conn = sqlite3.connect("database.db")
        self.cur = self.conn.cursor()
        self.selectedItem = selectedItem

        destinationPreviewWindow.setObjectName("destinationPreviewWindow")
        destinationPreviewWindow.setFixedSize(350, 480)
        self.mainWidget = QtWidgets.QWidget(destinationPreviewWindow)
        self.mainWidget.setGeometry(QtCore.QRect(0, 0, 350, 480))
        self.mainWidget.setStyleSheet("QWidget{\n"
"background-color:rgb(7, 25, 23);\n"
"}\n"
"QPushButton{\n"
"background-color:rgb(72, 168, 96);\n"
"color:rgb(0,0,0);\n"
"border:none;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(52, 148, 76);\n"
"}\n"
"QPlainTextEdit {\n"
"border: 1px solid rgb(128,128,128);\n"
"}")
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")

            # Name
        self.nameLayout = QtWidgets.QHBoxLayout()
        self.nameLayout.setObjectName("nameLayout")
        self.nameLabel = QtWidgets.QLabel(self.mainWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLayout.addWidget(self.nameLabel)
        self.namePlainTextEdit = QtWidgets.QPlainTextEdit(self.mainWidget)
        self.namePlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.namePlainTextEdit.setObjectName("namePlainTextEdit")
        self.nameLayout.addWidget(self.namePlainTextEdit)
        self.verticalLayout.addLayout(self.nameLayout)

            # Country
        self.countryLayout = QtWidgets.QHBoxLayout()
        self.countryLayout.setObjectName("countryLayout")
        self.countryLabel = QtWidgets.QLabel(self.mainWidget)
        self.countryLabel.setObjectName("countryLabel")
        self.countryLayout.addWidget(self.countryLabel)
        self.countryPlainTextEdit = QtWidgets.QPlainTextEdit(self.mainWidget)
        self.countryPlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.countryPlainTextEdit.setObjectName("countryPlainTextEdit")
        self.countryLayout.addWidget(self.countryPlainTextEdit)
        self.verticalLayout.addLayout(self.countryLayout)

            # Town
        self.townLayout = QtWidgets.QHBoxLayout()
        self.townLayout.setObjectName("townLayout")
        self.townLabel = QtWidgets.QLabel(self.mainWidget)
        self.townLabel.setObjectName("townLabel")
        self.townLayout.addWidget(self.townLabel)
        self.townPlainTextEdit = QtWidgets.QPlainTextEdit(self.mainWidget)
        self.townPlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.townPlainTextEdit.setObjectName("townPlainTextEdit")
        self.townLayout.addWidget(self.townPlainTextEdit)
        self.verticalLayout.addLayout(self.townLayout)

            # Description
        self.descLayout = QtWidgets.QHBoxLayout()
        self.descLayout.setObjectName("descLayout")
        self.descLabel = QtWidgets.QLabel(self.mainWidget)
        self.descLabel.setObjectName("descLabel")
        self.descLayout.addWidget(self.descLabel)
        self.descPlainTextEdit = QtWidgets.QPlainTextEdit(self.mainWidget)
        self.descPlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.descPlainTextEdit.setObjectName("descPlainTextEdit")
        self.descLayout.addWidget(self.descPlainTextEdit)
        self.verticalLayout.addLayout(self.descLayout)

            # Costs
        self.costsLayout = QtWidgets.QHBoxLayout()
        self.costsLayout.setObjectName("costsLayout")
        self.costsLabel = QtWidgets.QLabel(self.mainWidget)
        self.costsLabel.setObjectName("costsLabel")
        self.costsLayout.addWidget(self.costsLabel, 0, QtCore.Qt.AlignHCenter)
        self.costsStarsLayout = QtWidgets.QHBoxLayout()
        self.costsStarsLayout.setSpacing(3)
        self.costsStarsLayout.setObjectName("costsStarsLayout")
        self.costsStar_1 = QtWidgets.QPushButton(self.mainWidget)
        self.costsStar_1.setMinimumSize(QtCore.QSize(30, 30))
        self.costsStar_1.setMaximumSize(QtCore.QSize(30, 30))
        self.costsStar_1.setObjectName("costsStar_1")
        self.costsStarsLayout.addWidget(self.costsStar_1)
        self.costsStar_2 = QtWidgets.QPushButton(self.mainWidget)
        self.costsStar_2.setMinimumSize(QtCore.QSize(30, 30))
        self.costsStar_2.setMaximumSize(QtCore.QSize(30, 30))
        self.costsStar_2.setObjectName("costsStar_2")
        self.costsStarsLayout.addWidget(self.costsStar_2)
        self.costsStar_3 = QtWidgets.QPushButton(self.mainWidget)
        self.costsStar_3.setMinimumSize(QtCore.QSize(30, 30))
        self.costsStar_3.setMaximumSize(QtCore.QSize(30, 30))
        self.costsStar_3.setObjectName("costsStar_3")
        self.costsStarsLayout.addWidget(self.costsStar_3)
        self.costsStar_4 = QtWidgets.QPushButton(self.mainWidget)
        self.costsStar_4.setMinimumSize(QtCore.QSize(30, 30))
        self.costsStar_4.setMaximumSize(QtCore.QSize(30, 30))
        self.costsStar_4.setObjectName("costsStar_4")
        self.costsStarsLayout.addWidget(self.costsStar_4)
        self.costsStar_5 = QtWidgets.QPushButton(self.mainWidget)
        self.costsStar_5.setMinimumSize(QtCore.QSize(30, 30))
        self.costsStar_5.setMaximumSize(QtCore.QSize(30, 30))
        self.costsStar_5.setObjectName("costsStar_5")
        self.costsStarsLayout.addWidget(self.costsStar_5)
        self.costsLayout.addLayout(self.costsStarsLayout)
        self.verticalLayout.addLayout(self.costsLayout)

            # Profitability
        self.profitabilityLayout = QtWidgets.QHBoxLayout()
        self.profitabilityLayout.setObjectName("profitabilityLayout")
        self.profitabilityLabel = QtWidgets.QLabel(self.mainWidget)
        self.profitabilityLabel.setObjectName("profitabilityLabel")
        self.profitabilityLayout.addWidget(self.profitabilityLabel, 0, QtCore.Qt.AlignHCenter)
        self.profitabilityStarsLayout = QtWidgets.QHBoxLayout()
        self.profitabilityStarsLayout.setSpacing(3)
        self.profitabilityStarsLayout.setObjectName("profitabilityStarsLayout")
        self.profitabilityStar_1 = QtWidgets.QPushButton(self.mainWidget)
        self.profitabilityStar_1.setMinimumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_1.setMaximumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_1.setObjectName("profitabilityStar_1")
        self.profitabilityStarsLayout.addWidget(self.profitabilityStar_1)
        self.profitabilityStar_2 = QtWidgets.QPushButton(self.mainWidget)
        self.profitabilityStar_2.setMinimumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_2.setMaximumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_2.setObjectName("profitabilityStar_2")
        self.profitabilityStarsLayout.addWidget(self.profitabilityStar_2)
        self.profitabilityStar_3 = QtWidgets.QPushButton(self.mainWidget)
        self.profitabilityStar_3.setMinimumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_3.setMaximumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_3.setObjectName("profitabilityStar_3")
        self.profitabilityStarsLayout.addWidget(self.profitabilityStar_3)
        self.profitabilityStar_4 = QtWidgets.QPushButton(self.mainWidget)
        self.profitabilityStar_4.setMinimumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_4.setMaximumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_4.setObjectName("profitabilityStar_4")
        self.profitabilityStarsLayout.addWidget(self.profitabilityStar_4)
        self.profitabilityStar_5 = QtWidgets.QPushButton(self.mainWidget)
        self.profitabilityStar_5.setMinimumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_5.setMaximumSize(QtCore.QSize(30, 30))
        self.profitabilityStar_5.setObjectName("profitabilityStar_5")
        self.profitabilityStarsLayout.addWidget(self.profitabilityStar_5)
        self.profitabilityLayout.addLayout(self.profitabilityStarsLayout)
        self.verticalLayout.addLayout(self.profitabilityLayout)

            # Attractions
        self.attractionsLayout = QtWidgets.QHBoxLayout()
        self.attractionsLayout.setObjectName("attractionsLayout")
        self.attractionsLabel = QtWidgets.QLabel(self.mainWidget)
        self.attractionsLabel.setObjectName("attractionsLabel")
        self.attractionsLayout.addWidget(self.attractionsLabel, 0, QtCore.Qt.AlignHCenter)
        self.attractionsStarsLayout = QtWidgets.QHBoxLayout()
        self.attractionsStarsLayout.setSpacing(3)
        self.attractionsStarsLayout.setObjectName("attractionsStarsLayout")
        self.attractionsStar_1 = QtWidgets.QPushButton(self.mainWidget)
        self.attractionsStar_1.setMinimumSize(QtCore.QSize(30, 30))
        self.attractionsStar_1.setMaximumSize(QtCore.QSize(30, 30))
        self.attractionsStar_1.setObjectName("attractionsStar_1")
        self.attractionsStarsLayout.addWidget(self.attractionsStar_1)
        self.attractionsStar_2 = QtWidgets.QPushButton(self.mainWidget)
        self.attractionsStar_2.setMinimumSize(QtCore.QSize(30, 30))
        self.attractionsStar_2.setMaximumSize(QtCore.QSize(30, 30))
        self.attractionsStar_2.setObjectName("attractionsStar_2")
        self.attractionsStarsLayout.addWidget(self.attractionsStar_2)
        self.attractionsStar_3 = QtWidgets.QPushButton(self.mainWidget)
        self.attractionsStar_3.setMinimumSize(QtCore.QSize(30, 30))
        self.attractionsStar_3.setMaximumSize(QtCore.QSize(30, 30))
        self.attractionsStar_3.setObjectName("attractionsStar_3")
        self.attractionsStarsLayout.addWidget(self.attractionsStar_3)
        self.attractionsStar_4 = QtWidgets.QPushButton(self.mainWidget)
        self.attractionsStar_4.setMinimumSize(QtCore.QSize(30, 30))
        self.attractionsStar_4.setMaximumSize(QtCore.QSize(30, 30))
        self.attractionsStar_4.setObjectName("attractionsStar_4")
        self.attractionsStarsLayout.addWidget(self.attractionsStar_4)
        self.attractionsStar_5 = QtWidgets.QPushButton(self.mainWidget)
        self.attractionsStar_5.setMinimumSize(QtCore.QSize(30, 30))
        self.attractionsStar_5.setMaximumSize(QtCore.QSize(30, 30))
        self.attractionsStar_5.setObjectName("attractionsStar_5")
        self.attractionsStarsLayout.addWidget(self.attractionsStar_5)
        self.attractionsLayout.addLayout(self.attractionsStarsLayout)
        self.verticalLayout.addLayout(self.attractionsLayout)

            # Transport
        self.transportLayout = QtWidgets.QHBoxLayout()
        self.transportLayout.setObjectName("transportLayout")
        self.transportLabel = QtWidgets.QLabel(self.mainWidget)
        self.transportLabel.setObjectName("transportLabel")
        self.transportLayout.addWidget(self.transportLabel, 0, QtCore.Qt.AlignHCenter)
        self.transportStarsLayout = QtWidgets.QHBoxLayout()
        self.transportStarsLayout.setSpacing(3)
        self.transportStarsLayout.setObjectName("transportStarsLayout")
        self.transportStar_1 = QtWidgets.QPushButton(self.mainWidget)
        self.transportStar_1.setMinimumSize(QtCore.QSize(30, 30))
        self.transportStar_1.setMaximumSize(QtCore.QSize(30, 30))
        self.transportStar_1.setObjectName("transportStar_1")
        self.transportStarsLayout.addWidget(self.transportStar_1)
        self.transportStar_2 = QtWidgets.QPushButton(self.mainWidget)
        self.transportStar_2.setMinimumSize(QtCore.QSize(30, 30))
        self.transportStar_2.setMaximumSize(QtCore.QSize(30, 30))
        self.transportStar_2.setObjectName("transportStar_2")
        self.transportStarsLayout.addWidget(self.transportStar_2)
        self.transportStar_3 = QtWidgets.QPushButton(self.mainWidget)
        self.transportStar_3.setMinimumSize(QtCore.QSize(30, 30))
        self.transportStar_3.setMaximumSize(QtCore.QSize(30, 30))
        self.transportStar_3.setObjectName("transportStar_3")
        self.transportStarsLayout.addWidget(self.transportStar_3)
        self.transportStar_4 = QtWidgets.QPushButton(self.mainWidget)
        self.transportStar_4.setMinimumSize(QtCore.QSize(30, 30))
        self.transportStar_4.setMaximumSize(QtCore.QSize(30, 30))
        self.transportStar_4.setObjectName("transportStar_4")
        self.transportStarsLayout.addWidget(self.transportStar_4)
        self.transportStar_5 = QtWidgets.QPushButton(self.mainWidget)
        self.transportStar_5.setMinimumSize(QtCore.QSize(30, 30))
        self.transportStar_5.setMaximumSize(QtCore.QSize(30, 30))
        self.transportStar_5.setObjectName("transportStar_5")
        self.transportStarsLayout.addWidget(self.transportStar_5)
        self.transportLayout.addLayout(self.transportStarsLayout)
        self.verticalLayout.addLayout(self.transportLayout)

            # Gastronomy
        self.gastronomyLayout = QtWidgets.QHBoxLayout()
        self.gastronomyLayout.setObjectName("gastronomyLayout")
        self.gastronomyLabel = QtWidgets.QLabel(self.mainWidget)
        self.gastronomyLabel.setObjectName("gastronomyLabel")
        self.gastronomyLayout.addWidget(self.gastronomyLabel, 0, QtCore.Qt.AlignHCenter)
        self.gastronomyStarsLayout = QtWidgets.QHBoxLayout()
        self.gastronomyStarsLayout.setSpacing(3)
        self.gastronomyStarsLayout.setObjectName("gastronomyStarsLayout")
        self.gastronomyStar_1 = QtWidgets.QPushButton(self.mainWidget)
        self.gastronomyStar_1.setMinimumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_1.setMaximumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_1.setObjectName("gastronomyStar_1")
        self.gastronomyStarsLayout.addWidget(self.gastronomyStar_1)
        self.gastronomyStar_2 = QtWidgets.QPushButton(self.mainWidget)
        self.gastronomyStar_2.setMinimumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_2.setMaximumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_2.setObjectName("gastronomyStar_2")
        self.gastronomyStarsLayout.addWidget(self.gastronomyStar_2)
        self.gastronomyStar_3 = QtWidgets.QPushButton(self.mainWidget)
        self.gastronomyStar_3.setMinimumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_3.setMaximumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_3.setObjectName("gastronomyStar_3")
        self.gastronomyStarsLayout.addWidget(self.gastronomyStar_3)
        self.gastronomyStar_4 = QtWidgets.QPushButton(self.mainWidget)
        self.gastronomyStar_4.setMinimumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_4.setMaximumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_4.setObjectName("gastronomyStar_4")
        self.gastronomyStarsLayout.addWidget(self.gastronomyStar_4)
        self.gastronomyStar_5 = QtWidgets.QPushButton(self.mainWidget)
        self.gastronomyStar_5.setMinimumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_5.setMaximumSize(QtCore.QSize(30, 30))
        self.gastronomyStar_5.setObjectName("gastronomyStar_5")
        self.gastronomyStarsLayout.addWidget(self.gastronomyStar_5)
        self.gastronomyLayout.addLayout(self.gastronomyStarsLayout)
        self.verticalLayout.addLayout(self.gastronomyLayout)

            # Landscapes
        self.landscapesLayout = QtWidgets.QHBoxLayout()
        self.landscapesLayout.setObjectName("landscapesLayout")
        self.lanscapesLabel = QtWidgets.QLabel(self.mainWidget)
        self.lanscapesLabel.setObjectName("lanscapesLabel")
        self.landscapesLayout.addWidget(self.lanscapesLabel, 0, QtCore.Qt.AlignHCenter)
        self.landscapesStarsLayout = QtWidgets.QHBoxLayout()
        self.landscapesStarsLayout.setSpacing(3)
        self.landscapesStarsLayout.setObjectName("landscapesStarsLayout")
        self.lanscapesStar_1 = QtWidgets.QPushButton(self.mainWidget)
        self.lanscapesStar_1.setMinimumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_1.setMaximumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_1.setObjectName("lanscapesStar_1")
        self.landscapesStarsLayout.addWidget(self.lanscapesStar_1)
        self.lanscapesStar_2 = QtWidgets.QPushButton(self.mainWidget)
        self.lanscapesStar_2.setMinimumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_2.setMaximumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_2.setObjectName("lanscapesStar_2")
        self.landscapesStarsLayout.addWidget(self.lanscapesStar_2)
        self.lanscapesStar_3 = QtWidgets.QPushButton(self.mainWidget)
        self.lanscapesStar_3.setMinimumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_3.setMaximumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_3.setObjectName("lanscapesStar_3")
        self.landscapesStarsLayout.addWidget(self.lanscapesStar_3)
        self.lanscapesStar_4 = QtWidgets.QPushButton(self.mainWidget)
        self.lanscapesStar_4.setMinimumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_4.setMaximumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_4.setObjectName("lanscapesStar_4")
        self.landscapesStarsLayout.addWidget(self.lanscapesStar_4)
        self.lanscapesStar_5 = QtWidgets.QPushButton(self.mainWidget)
        self.lanscapesStar_5.setMinimumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_5.setMaximumSize(QtCore.QSize(30, 30))
        self.lanscapesStar_5.setObjectName("lanscapesStar_5")
        self.landscapesStarsLayout.addWidget(self.lanscapesStar_5)
        self.landscapesLayout.addLayout(self.landscapesStarsLayout)
        self.verticalLayout.addLayout(self.landscapesLayout)

            # Avarge score
        self.avarge_scoreLabel = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.avarge_scoreLabel.setFont(font)
        self.avarge_scoreLabel.setObjectName("avarge_scoreLabel")
        self.verticalLayout.addWidget(self.avarge_scoreLabel)

        self.loadData()

        self.retranslateUi(destinationPreviewWindow)
        QtCore.QMetaObject.connectSlotsByName(destinationPreviewWindow)

    def retranslateUi(self, destinationPreviewWindow):
        _translate = QtCore.QCoreApplication.translate
        destinationPreviewWindow.setWindowTitle(_translate("destinationPreviewWindow", "Destination Preview"))
        self.nameLabel.setText(_translate("destinationPreviewWindow", "Name:"))
        self.countryLabel.setText(_translate("destinationPreviewWindow", "Country:"))
        self.townLabel.setText(_translate("destinationPreviewWindow", "Town:"))
        self.descLabel.setText(_translate("destinationPreviewWindow", "Description:"))
        self.costsLabel.setText(_translate("destinationPreviewWindow", "Costs: "))
        self.costsStar_1.setText(_translate("destinationPreviewWindow", "★"))
        self.costsStar_2.setText(_translate("destinationPreviewWindow", "★"))
        self.costsStar_3.setText(_translate("destinationPreviewWindow", "★"))
        self.costsStar_4.setText(_translate("destinationPreviewWindow", "★"))
        self.costsStar_5.setText(_translate("destinationPreviewWindow", "★"))
        self.profitabilityLabel.setText(_translate("destinationPreviewWindow", "Profitability:"))
        self.profitabilityStar_1.setText(_translate("destinationPreviewWindow", "★"))
        self.profitabilityStar_2.setText(_translate("destinationPreviewWindow", "★"))
        self.profitabilityStar_3.setText(_translate("destinationPreviewWindow", "★"))
        self.profitabilityStar_4.setText(_translate("destinationPreviewWindow", "★"))
        self.profitabilityStar_5.setText(_translate("destinationPreviewWindow", "★"))
        self.attractionsLabel.setText(_translate("destinationPreviewWindow", "Attracions:"))
        self.attractionsStar_1.setText(_translate("destinationPreviewWindow", "★"))
        self.attractionsStar_2.setText(_translate("destinationPreviewWindow", "★"))
        self.attractionsStar_3.setText(_translate("destinationPreviewWindow", "★"))
        self.attractionsStar_4.setText(_translate("destinationPreviewWindow", "★"))
        self.attractionsStar_5.setText(_translate("destinationPreviewWindow", "★"))
        self.transportLabel.setText(_translate("destinationPreviewWindow", "Transport:"))
        self.transportStar_1.setText(_translate("destinationPreviewWindow", "★"))
        self.transportStar_2.setText(_translate("destinationPreviewWindow", "★"))
        self.transportStar_3.setText(_translate("destinationPreviewWindow", "★"))
        self.transportStar_4.setText(_translate("destinationPreviewWindow", "★"))
        self.transportStar_5.setText(_translate("destinationPreviewWindow", "★"))
        self.gastronomyLabel.setText(_translate("destinationPreviewWindow", "Gastronomy:"))
        self.gastronomyStar_1.setText(_translate("destinationPreviewWindow", "★"))
        self.gastronomyStar_2.setText(_translate("destinationPreviewWindow", "★"))
        self.gastronomyStar_3.setText(_translate("destinationPreviewWindow", "★"))
        self.gastronomyStar_4.setText(_translate("destinationPreviewWindow", "★"))
        self.gastronomyStar_5.setText(_translate("destinationPreviewWindow", "★"))
        self.lanscapesLabel.setText(_translate("destinationPreviewWindow", "Landscapes:"))
        self.lanscapesStar_1.setText(_translate("destinationPreviewWindow", "★"))
        self.lanscapesStar_2.setText(_translate("destinationPreviewWindow", "★"))
        self.lanscapesStar_3.setText(_translate("destinationPreviewWindow", "★"))
        self.lanscapesStar_4.setText(_translate("destinationPreviewWindow", "★"))
        self.lanscapesStar_5.setText(_translate("destinationPreviewWindow", "★"))
        self.avarge_scoreLabel.setText(_translate("destinationPreviewWindow", "Avarge score: "))

    def loadData(self):
        self.cur.execute("SELECT * FROM destinations WHERE name=?", (self.selectedItem,))
        data = self.cur.fetchall()[0]

        self.namePlainTextEdit.setPlainText(data[1])
        self.namePlainTextEdit.setReadOnly(True)

        self.countryPlainTextEdit.setPlainText(data[2])
        self.countryPlainTextEdit.setReadOnly(True)

        self.townPlainTextEdit.setPlainText(data[3])
        self.townPlainTextEdit.setReadOnly(True)

        self.descPlainTextEdit.setPlainText(data[4])
        self.descPlainTextEdit.setReadOnly(True)

        if data[5] != None:
            for i in range(1,data[5]):
                pass